### ISSUE TITLE
AttributeError("'bool' object has no attribute 'get'")

### ISSUE THREAD

**Issue by ghost** [mcw0/DahuaConsole#10]
└─$ python3 Console.py --logon netkeyboard --rhost  --rport 8081 --proto http
[*] [Dahua Debug Console 2019-2021 bashis <mcw noemail eu>]
[*] logon type "netkeyboard" with proto "http" at 
[▘] Dahua Debug Console: Trying
[+] Login: Success
[+] keepAlive thread: Started
AttributeError("'bool' object has no attribute 'get'")
[-] [MainConsole]
[*] All done

Using Linux and latest version of Console.

**Comment by mcw0** [comment]
Known issue with http and very old Dahua stuff (2014ish), and besides, I see you attacking a device that seems not to belong to you, so I won't spend time on this.
