### ISSUE TITLE
Password hash

### ISSUE THREAD

**Issue by Yev-henii** [mcw0/DahuaConsole#17]
I remotely connected to the DVR and got access to the console which allows me to execute some commands.  Along with this, I see the inscription "Attack console failed. Using local only".  Why do I see this inscription but at the same time I can use the console and get some information about the device.  What command should I use to add a new user or get the password hash from the admin user?

![IMG_20211116_163810_503](https://user-images.githubusercontent.com/94464791/142007223-30e54852-59bc-4908-9670-7bdbdd199b92.jpg)

**Comment by p2p-sys** [comment]
Dhip protocol for port 5000

**Comment by Yev-henii** [comment]
In the case of port 5000, this does not work at all.

![IMG_20211116_172033_543](https://user-images.githubusercontent.com/94464791/142013872-aef9c32d-a356-46cc-b20e-285cec46f3e0.jpg)

**Comment by mcw0** [comment]
> I remotely connected to the DVR and got access to the console which allows me to execute some commands.
I see it is a NVR (Class: NVR)

> Along with this, I see the inscription "Attack console failed. Using local only". Why do I see this inscription but at the same time I can use the console and get some information about the device.
In most devices there is builtin "Debug Console", and that we trying to attach. Working fine with IPC/VTH/VTO/SD... etc, DVR/NVR has builtin "Debug Console" as well, but it will not allow us to attach to that. To be able to use other commands, that has been researched and implemented in the python script, the script will accept that we cannot attach to the builtin "Debug Console", the script will inform and just continue.

>What command should I use to add a new user or get the password hash from the admin user?
That has not been implemented in the script on purpose, the research and script is concentrated on things that you cannot normally access from Web GUI, where you can add/remove/modify users.
