### ISSUE TITLE
[p2p] send: AttributeError("module 'select' has no attribute 'POLLIN'")

### ISSUE THREAD

**Issue by pexes** [mcw0/DahuaConsole#26]
Some issues with POLLIN 
![image](https://user-images.githubusercontent.com/32525150/157877810-547c370b-0ec3-4d39-b793-7d3b54581532.png)

**Comment by redowan99** [comment]
I have also same problem.

**Comment by mcw0** [comment]
Correct, I develop only w/ Linux, and the POLLIN is a Windows python issue, and not with this script itself.
