### ISSUE TITLE
AttributeError("'NoneType' object has no attribute 'get'")

### ISSUE THREAD

**Issue by smsalert-mobi** [mcw0/DahuaConsole#32]
Hi, 
i'm trying to connect to https://www.dahuasecurity.com/products/All-Products/Access-Control--Time-Attendance/Access-Control/Standalone/ASI1201E/ASI1201E-D

but i get this error.
PS: I am looking for a way to connect it to homeassistant.

 ./Console.py --logon netkeyboard --rhost 192.168.90.5  --rport 37777 --auth admin:****** -d
[*] [Dahua Debug Console 2019-2021 bashis <mcw noemail eu>]
[*] logon type "netkeyboard" with proto "dhip" at 192.168.90.5:37777
[+] Opening connection to 192.168.90.5 on port 37777: Done
[./......] Dahua Debug Console: Trying
[+] Login: Success
[BEGIN SEND (192.168.90.5)] <------------------1803------------------>
20000000|44484950|00000000|00000000|91000000|00000000|91000000|00000000
{"method": "global.login", "params": {"userName": "admin", "password": "", "clientType": "Web3.0", "loginType": "Direct"}, "id": 0, "session": 0}
[ END  SEND (192.168.90.5)] <------------------1803------------------>
[BEGIN RECV (192.168.90.5)] <------------------1919------------------>
20000000|44484950|d710c601|00000000|ac000000|00000000|ac000000|00000000
{ "result": false, "params": { "realm": "Login to ASI1201E", "random": "29757655", "encryption": "Default" }, "error": { "code": 268632079 }, "id": 0, "session": 29757655 }
[ END  RECV (192.168.90.5)] <------------------1919------------------>
[BEGIN SEND (192.168.90.5)] <------------------1803------------------>
20000000|44484950|d710c601|01000000|0b010000|00000000|0b010000|00000000
{"method": "global.login", "params": {"userName": "admin", "ipAddr": "127.0.0.1", "loginType": "Direct", "clientType": "NetKeyboard", "authorityType": "Default", "passwordType": "Default", "password": "61C31760B8AAB860833EE2083568AA60"}, "id": 1, "session": 29757655}
[ END  SEND (192.168.90.5)] <------------------1803------------------>
[BEGIN RECV (192.168.90.5)] <------------------1919------------------>
20000000|44484950|d710c601|01000000|40000000|00000000|40000000|00000000
{ "result": true, "params": null, "id": 1, "session": 29757655 }
[ END  RECV (192.168.90.5)] <------------------1919------------------>
[BEGIN SEND (192.168.90.5)] <------------------1803------------------>
20000000|44484950|d710c601|02000000|5c000000|00000000|5c000000|00000000
{"method": "userManager.getActiveUserInfoAll", "params": null, "id": 2, "session": 29757655}
[ END  SEND (192.168.90.5)] <------------------1803------------------>
[+] keepAlive thread: Started
[BEGIN RECV (192.168.90.5)] <------------------1919------------------>
20000000|44484950|d710c601|02000000|2c000000|00000000|2c000000|00000000
{ "result": false, "id": 2, "params": null }
[ END  RECV (192.168.90.5)] <------------------1919------------------>
AttributeError("'NoneType' object has no attribute 'get'")
[-] [MainConsole]
[*] All done
[*] Closed connection to 192.168.90.5 port 37777

**Comment by mcw0** [comment]
Guess you might use very old Firmware, if so upgrade if you can,

You can see when connecting:
[BEGIN RECV (192.168.90.5)] <------------------1919------------------>
20000000|44484950|d710c601|02000000|2c000000|00000000|2c000000|00000000
{ "result": false, "id": 2, "params": null }
[ END RECV (192.168.90.5)] <------------------1919------------------>

Remote device return "false", and "params" are null.

Meaning remote device has no method called "userManager.getActiveUserInfoAll".

You could try to use: --logon old_3des (or simply comment out at https://github.com/mcw0/DahuaConsole/blob/master/net.py#L442
)

BTW, 
1) no need to use: --logon netkeyboard when you have credentials, as this option will bypass the need for --auth.
2) --logon netkeyboard will not work with DVRIP (TCP/37777), works only with DHIP or HTTP/HTTPS

I also see the script trying to use DHIP on port 37777 "logon type "netkeyboard" with proto "dhip" at 192.168.90.5:37777" - will not work.

I would suggest you to try: ./Console.py --proto dvrip --rhost 192.168.90.5 --rport 37777 --auth admin:****** -d
Since you trying to connect on port TCP/37777

**Comment by smsalert-mobi** [comment]
The device does not communicate on dvrip, but dhip
As you can see above login works but just returns params "null", and that is not handled in the library.

Device firmware is the latest available, from 2019

For example in net.py if i do this

-            if dh_data.get('params').get('users') is not None:
+            if dh_data.get('params') is not None and dh_data.get('params').get('users') is not None:

Login works and get the menu of commands.  I can even get  some device details.
Doing actions like doorUnlock because list_service fails and RemoteServicesCache is not expected to be null.

Going further with this, i attached you a communication log debug from SmartAc PSS and dahua device at the end, and you will see 
that system.listService is not working, but accessControl.listMethod instead results in a list of methods.

Login also is done like this, i can see DHIP in the headers.

![login](https://user-images.githubusercontent.com/97119259/193744367-8a22d915-0652-4eeb-b12a-63c26067aa22.png)
![login_response](https://user-images.githubusercontent.com/97119259/193744487-18033588-7779-48ee-8598-89cd9440c6f9.png)


[export_packets.txt](https://github.com/mcw0/DahuaConsole/files/9703093/export_packets.txt)

**Comment by mcw0** [comment]
Very interesting, one of my earlier questions was about "stochasticId", I have seen that in the FW and also noted that in "dahua_logon_modes.py" but not seen it before in any traffic - until now, in your first image.
FYI, DHIP isn't offical Dahua API, so I do expect  some changes... "system.listService" was found to give whole list of methods and is quite handy to see what's "supported" (not everything is supported, despite it may be in the list), but in your device it seems being removed.
The "accessControl.listMethod " gives "only" a list of methods related to "accessControl".
Many thanks for sharing this, very interesting!

**Comment by smsalert-mobi** [comment]
and can you help out with an update on the library in the future? i do not know python to update it and make changes, i mainly use PHP...

**Comment by mcw0** [comment]
Working on to split the front end (Console.py) and the library, so the library could be used alone. So, yes, indeed I am taking this with me on that work.
