### ISSUE TITLE
global.getCurrentTime does not exist on every camera, crashing program

### ISSUE THREAD

**Issue by LukaszMoskala** [mcw0/DahuaConsole#4]
Hi,

Just to let you (and anyone else who may have the same problem) know, on line 490 of `net.py` there is:
```python
dh_data.get('global.getCurrentTime').get('params').get('time'),
```
This is not working with my camera. Maybe because mine firmware is from 2014.

So anyway, I changed:
```python
        log.info("Remote Model: {}, Class: {}, Time: {}".format(
            self.DeviceType,
            self.DeviceClass,
            dh_data.get('global.getCurrentTime').get('params').get('time'),
        ))
```
To:
```python
        log.info("Remote Model: {}, Class: {}".format(
            self.DeviceType,
            self.DeviceClass
        ))
```

And it's working. I'd open pull request for that, but it's already late for me. You can change this in your code if you want.

**Comment by mcw0** [comment]
Cool, many thanks, will try to fix that with 'if' statement so it will not crash.

BTW, you may want to add "magic":"0x1234" to all outgoing JSON requests with DHIP protocol, w/o that DHIP will most probably not work with your old Firmware.
